version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    container_name: springshop-db
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local